### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by ashutoshsamal** [josephmachado/beginner_de_project#15]
hi,
I want to build this project on my own on GCP and wanted to know where can i find all the dataset used in this project

**Comment by josephmachado** [comment]
Hi, Its available from S3 at this location `s3://start-data-engg/data.zip`. You can download it and upload to GCP or store where you prefer.

[command to download to local fs](https://github.com/josephmachado/beginner_de_project/blob/7ac2b303798ca8da97e602106ff8a7d32efd32d3/setup_infra.sh#L31-L33)

**Comment by ashutoshsamal** [comment]
HI,
I am not able to access this bucket can you please provide the zip file in a google drive or something. Or can you send me the full procedure to download data
