### ISSUE TITLE
Dags keeps failing

### ISSUE THREAD

**Issue by Adematics** [josephmachado/beginner_de_project#20]
Hey @josephmachado I need your help on this..

I tried running my own spark script using your framework after changing the needed files but my dags keeps failing....please I really would need your assistance... 

Below is the link to the issue am currently facing....
[Link !](https://github.com/Adematics/beginners_batch_project)

**Comment by josephmachado** [comment]
Hey @Adematics  I don't think this is an issue with this repo, since the code has been changed. Therefore I am closing this issue.
