### ISSUE TITLE
error: command make infra-up =>  could not start transaction: dial tcp ip:5439: connect: connection timed out

### ISSUE THREAD

**Issue by Stefen-Taime** [josephmachado/beginner_de_project#25]
│   with redshift_schema.external_from_glue_data_catalog,
│   on main.tf line 170, in resource "redshift_schema" "external_from_glue_data_catalog":
│  170: resource "redshift_schema" "external_from_glue_data_catalog" {
│ 
╵
Makefile:45: recipe for target 'infra-up' failed
make: *** [infra-up] Error 1

**Comment by josephmachado** [comment]
Hey @Stefen-Taime Do you have any specific security groups? This looks like terraform couldn't reach the glue catalog.

**Comment by Stefen-Taime** [comment]
Security group on my ec2?

**Comment by josephmachado** [comment]
No, the redshift cluster group. Could you please paste the entire error message? And check your AWS UI to see if you have Redshift cluster running?

**Comment by josephmachado** [comment]
Closing this, due to no response
