### ISSUE TITLE
Error: could not start transaction: dial tcp 23.22.231.56:5439: connect: connection timed out

### ISSUE THREAD

**Issue by Sameerna** [josephmachado/beginner_de_project#29]
Error: could not start transaction: dial tcp 23.22.231.56:5439: connect: connection timed out
│
│   with redshift_schema.external_from_glue_data_catalog,
│   on main.tf line 170, in resource "redshift_schema" "external_from_glue_data_catalog":
│  170: resource "redshift_schema" "external_from_glue_data_catalog" {

I have been working in this for many days now but There no luck. 
I tried to identify what actually this IP ( 23.22.231.56) 

seems like this endpoint is causing the problem 
 "Endpoint": {
                "Address": "sde-redshift-cluster.ccieif6ln9js.us-east-1.redshift.amazonaws.com",
                "Port": 5439
            },
            
          
I can confirm that this is the one by trying to ping it as  I am able to see the IP mentioned in the error. 

 ping sde-redshift-cluster.ccieif6ln9js.us-east-1.redshift.amazonaws.com
PING ec2-23-22-231-56.compute-1.amazonaws.com (23.22.231.56) 56(84) bytes of data.
 -------------------------------------------------------------------------------------------------------------------------------

aws redshift describe-clusters --cluster-identifier sde-redshift-cluster
{
    "Clusters": [
        {
            "ClusterIdentifier": "sde-redshift-cluster",
            "NodeType": "dc2.large",
            "ClusterStatus": "available",
            "ClusterAvailabilityStatus": "Available",
            "MasterUsername": "sde_user",
            "DBName": "",
            "Endpoint": {
                "Address": "sde-redshift-cluster.ccieif6ln9js.us-east-1.redshift.amazonaws.com",
                "Port": 5439
            },
            "ClusterCreateTime": "2023-05-01T05:30:17.926Z",
            "AutomatedSnapshotRetentionPeriod": 1,
            "ManualSnapshotRetentionPeriod": -1,
            "ClusterSecurityGroups": [],
            "VpcSecurityGroups": [
                {
                    "VpcSecurityGroupId": "sg-0a32ec33fa085f52d",
                    "Status": "active"
                }
            ],
            "ClusterParameterGroups": [
                {
                    "ParameterGroupName": "default.redshift-1.0",
                    "ParameterApplyStatus": "in-sync"
                }
            ],
            "ClusterSubnetGroupName": "default",
            "VpcId": "vpc-0bdf0c67e3b0c8093",
            "AvailabilityZone": "us-east-1e",
            "PreferredMaintenanceWindow": "wed:03:30-wed:04:00",
            "PendingModifiedValues": {},
            "ClusterVersion": "1.0",
            "AllowVersionUpgrade": true,
            "NumberOfNodes": 1,
            "PubliclyAccessible": true,
            "Encrypted": false,
            "ClusterPublicKey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCJiSS/9+VF3Nk0FCdZReWLjPkGjDuG3jzJE7I6+SH3CBNKVEV2TzoCdZ4tw3h+675CgNIGkN3ICk6qMzBepJxZcJ7oHfu6R0kF7x2gKHIyACl/hOmUZLBUSTGWF8ix768F25a++9XZwbaCDkNpOq+7TlipS35dMaRpuVWRVND7Dkyk7u4saWSx2U++iOYmyo7tTbn8XCMtfiy6qeukFpFCEcUfynfN11Tz+ycsmXJuudjBdBz3g17vHGlLJgEmJg5hRo3HuhsIB8/OrZgTrZAO7JJX0wBupliPt3KjyoLkjGoSq0GWr0icYv7SD+UC/c6mIEt7og5IdnFcZwH8dZAT Amazon-Redshift\n",
            "ClusterNodes": [
                {
                    "NodeRole": "SHARED",
                    "PrivateIPAddress": "172.31.51.149",
                    "PublicIPAddress": "3.213.178.124"
                }
            ],
            "ClusterRevisionNumber": "49780",
            "Tags": [],
            "EnhancedVpcRouting": false,
            "IamRoles": [
                {
                    "IamRoleArn": "arn:aws:iam::460318025676:role/sde_redshift_iam_role",
                    "ApplyStatus": "in-sync"
                }
            ],
            "MaintenanceTrackName": "current",
            "DeferredMaintenanceWindows": [],
            "NextMaintenanceWindowStartTime": "2023-05-03T03:30:00Z"
        }
    ]
}

---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Sameerna** [comment]
I have been working on this for many days now but seems like there's no luck.
I tried to figure out what this IP is ( 23.22.231.56). 

Typo

**Comment by Sameerna** [comment]
Issue resolved, 
FIx - opened the port for the required security group by adding inbound rule

**Comment by Sameerna** [comment]
opened the port for the required security group by adding inbound rule

**Comment by trantuanngoc** [comment]
@Sameerna can you share the file main.tf. I got the same issue
