### ISSUE TITLE
Stuck at "attaching to airflow_init_1"

### ISSUE THREAD

**Issue by rab241** [josephmachado/beginner_de_project#7]
Thank you  for the help! I figured out on my own some issues and also cant find updated instructions on setting up the environments. Here is a screenshot of my issue. I also am getting that the username and password  for airflow is wrong. I also dont understand where and when to enter that. I would appreciate the help!
<img width="695" alt="Screen Shot 2021-06-22 at 8 07 09 PM" src="https://user-images.githubusercontent.com/84033599/123015163-c1cda600-d395-11eb-98e0-e9ed1d2b7ca8.png">

**Comment by josephmachado** [comment]
Hi @rab241  It looks like the postgres container is not running. Can you 
1. tear down infra with `./tear_down_infra.sh {your-bucket-name}` and then
2. Increase docker size as shown here https://github.com/apache/airflow/issues/14365#issuecomment-785267821, restart docker and `./setup_infra.sh {your-bucket-name}`

If the issue still exists can you copy paste the logs ?

**Comment by rab241** [comment]
Thank you that seemed to work! However it is still stuck at attaching to airflow-init_1 and nothing seems to happen
<img width="563" alt="Screen Shot 2021-06-22 at 11 25 16 PM" src="https://user-images.githubusercontent.com/84033599/123030786-5265af80-d3b1-11eb-82f3-b7d107170a47.png">

**Comment by josephmachado** [comment]
@rab241 It takes a few min(1-2), can you lmk how long you waited ?

**Comment by rab241** [comment]
I waited around 10 minutes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dennisgsmith** [comment]
@rab241 I had this same issue when rerunning `./setup_infra.sh`. Clearing the Docker cache and rerunning the script solved it for me: `docker system prune --volumes`

Alternatively, maybe adding the `--force-recreate` flag to the docker compose command will fix this but I haven't tried it out yet.

**Comment by dennisgsmith** [comment]
@josephmachado I was able to recreate the issue by running the `./setup_infra.sh` script, canceling it after the image builds, and then re-running the script. Modifying `docker compose up airflow-init --force-recreate` with this flag fixed the issue without having to manually clear my docker cache. If this solves the problem, I can submit a PR if you'd like.

**Comment by rab241** [comment]
Hi, thanks for all the help! However, this is the issue that comes up when I ran the airflow recreate 
<img width="780" alt="Screen Shot 2021-06-23 at 9 08 00 AM" src="https://user-images.githubusercontent.com/84033599/123102111-b82e5780-d402-11eb-9d97-58c0d000f882.png">

**Comment by josephmachado** [comment]
Thank you. That would be amazing @dennisgsmith

**Comment by josephmachado** [comment]
@rab241 Think the Postgres container is still running(hence the 5432 port in use already), can you restart the docker container and try again using this https://github.com/josephmachado/beginner_de_project/issues/7#issuecomment-866790709

**Comment by rab241** [comment]
I had done that and redid it and the same 5432 port in use is still the error

**Comment by dennisgsmith** [comment]
@rab241 If you execute `lsof -n -i:5432 | grep LISTEN` you can see whatever is taking up that port. If you have a system version of Postgres using the port will need to shut it down.

**Comment by rab241** [comment]
nothing shows up when I run that command

**Comment by dennisgsmith** [comment]
@rab241 
What if you run as sudo? `sudo lsof -i :5432`

If there is anything running, you should be able to kill it by specifying the PID
`sudo kill -9 PID`
[dwyl/learn-postgresql#60](https://github.com/dwyl/learn-postgresql/issues/60#issuecomment-590024646)

You could also try killing it by specifying by postgres user without a PID
`sudo pkill -u postgres`
[PostgresApp/PostgresApp#197 (comment)](https://github.com/PostgresApp/PostgresApp/issues/197#issuecomment-474534056)

**Comment by josephmachado** [comment]
@rab241 could you run `docker ps` and paste the output here please.

**Comment by rab241** [comment]
<img width="1158" alt="Screen Shot 2021-06-23 at 9 59 28 AM" src="https://user-images.githubusercontent.com/84033599/123110029-b916b780-d409-11eb-936c-2de49b0ca623.png">

**Comment by rab241** [comment]
So while I was setting up again, it got stuck again at attaching to airflow. I went into the docker and manually ran the different containers which started to run the airflow init and then reached to points where my  s3 bucket needed more permissions. I created the  permissions and  now it is looping on this error: An error occurred (ClusterNotFound) when calling the DescribeClusters operation: Cluster sde-batch-de-project not found.

it  keeps sleeping  for 60  seconds and checking

**Comment by rab241** [comment]
I cancelled and  tore down the infrastructure and this error occurred:  An error occurred (NoSuchEntity) when calling the DetachRolePolicy operation: The role with name sde-spectrum-redshift cannot be found.
Dissociating AWSGlueConsoleFullAccess policy from sde-spectrum-redshift role

**Comment by rab241** [comment]
with manually running airflow-init, and postgres this happens before what I just mentioned 
<img width="511" alt="Screen Shot 2021-06-23 at 10 46 19 AM" src="https://user-images.githubusercontent.com/84033599/123118012-44934700-d410-11eb-942a-b1ab3bcbbe1c.png">
<img width="1103" alt="Screen Shot 2021-06-23 at 10 46 42 AM" src="https://user-images.githubusercontent.com/84033599/123118086-54ab2680-d410-11eb-9759-923fe52d6930.png">

**Comment by rab241** [comment]
It successfully set up  containers and airflow after completely trying again
<img width="1386" alt="Screen Shot 2021-06-23 at 10 55 12 AM" src="https://user-images.githubusercontent.com/84033599/123120064-09921300-d412-11eb-980f-a88d5d7c29ef.png">


Then I ran this and the airflow password worked but then I dont know what to do now
pgcli -h localhost -p 5432 -U airflow
<img width="1438" alt="Screen Shot 2021-06-23 at 10 59 23 AM" src="https://user-images.githubusercontent.com/84033599/123120162-1878c580-d412-11eb-94cc-be94d5e860cb.png">

**Comment by rab241** [comment]
I realized it is working now lol! Thanks for all your help!
