### ISSUE TITLE
psql: error: could not connect to server

### ISSUE THREAD

**Issue by spyne40** [josephmachado/beginner_de_project#8]
Getting this error toward the end of the setup shell script, seemingly where we upload sql tables or data to redshift. It seems I'm unable to connect to the Redshift server/port combination specified in the variables section of setup_infra.sh.  

psql -f ./redshiftsetup.sql postgres://sdeuser:sdeP0ssword0987@sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com:5439/dev

psql: error: could not connect to server: Operation timed out Is the server running on host "sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com" (44.236.207.102) and accepting TCP/IP connections on port 5439?

I'm looking at AWS gui redshift section. This URL seems to correspond exactly with the endpoint url sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com:5439/dev

so perhaps an issue with the port. i will reach out to AWS soon if i can't figure it out. please let me know if you can think of anything! thanks

**Comment by josephmachado** [comment]
@spyne40 Can you try `sde_user` as user name. So this 

```bash
psql -f ./redshiftsetup.sql postgres://sde_user@sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com:5439/dev
```

**Comment by spyne40** [comment]
yeah that's actually what i've been using, not sure how i removed the underscore from here. Here is the command agan:
```
(base) steve@MacBook-Pro beginner_de_project % psql -f ./redshift_setup.sql postgres://sde_user:sdeP0ssword0987@sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com:5439/dev
psql: error: could not connect to server: Operation timed out
	Is the server running on host "sde-batch-de-project.cinry7pfnj94.us-west-2.redshift.amazonaws.com" (44.236.207.102) and accepting
	TCP/IP connections on port 5439?
```
So i confirmed my cluster is publicly accessible. Just going through this trouble shooting now: https://aws.amazon.com/premiumsupport/knowledge-center/cannot-connect-redshift-cluster/

**Comment by spyne40** [comment]
Joseph, i figured out psql (postgres) was not actually running on my own labtap -- this is definitely linked to the psql instructions which i could not figure out entirely. If you look here: https://blog.timescale.com/tutorials/how-to-install-psql-on-mac-ubuntu-debian-windows/

brew link --force libpq ail
Error: No such keg: /usr/local/Cellar/ail

Does this mean anything to you? There is very little discussion on this online. I tried installing ail, and it's not recognized. 

I then installed postgresql directly, and got psql running (this took some time too), modified the credential configs to allow all connection,  but still it came back to this same error of "psql: error: could not connect to server: Operation timed out"

**Comment by spyne40** [comment]
Joseph -- i ended up uninstalling everything then reinstalling. Also went with a homebrew install postgresql  instead of psql. And then i adjusted the inbound route rule to include 0/0.0.0.0, like someone had said on the main page comments.

Noticed a few things:

1) the aws create bucket command fails. here is one that works:
aws s3api create-bucket --bucket newbucket --region us-west-2 --create-bucket-configuration LocationConstraint=us-west-2

2) ./redshiftsetup.sql needs to be changed to ./redshift_setup.sql in the psql command

3) this redshift setup sql is givng me issues setting up the database in Redshift, as i cannot see it there. Still debugging. it's odd, given my terminal output seemed it worked:
psql:./redshift_setup.sql:2: INFO:  External database "spectrumdb" created
```
CREATE SCHEMA
psql:./redshift_setup.sql:3: INFO:  External table "user_purchase_staging" does not exist and will be skipped
DROP TABLE
CREATE EXTERNAL TABLE
psql:./redshift_setup.sql:19: INFO:  External table "classified_movie_review" does not exist and will be skipped
DROP TABLE
CREATE EXTERNAL TABLE
psql:./redshift_setup.sql:25: INFO:  Table "user_behavior_metric" does not exist and will be skipped
DROP TABLE
CREATE TABLE

```
