### ISSUE TITLE
user_behaviour.py vs using DAG? 

### ISSUE THREAD

**Issue by spyne40** [josephmachado/beginner_de_project#9]
Hi Joseph,

Having a hard time understanding how to execute all the loads (step 5 onward). So i see you've updated the user_behaviour.py to pull in EMR ID and bucket name dynamically, therefore it seems we wouldn't need to update that. 

So, basically, to get the tasks running, what is needed? I have just clicked "run DAG" on airflow -- it shows a running status however it doesn't seem that any of the tasks are launching. 

Thanks,
Steve

**Comment by spyne40** [comment]
wow, so even after i run the DAG in airflow GUI, still have to unpause it (paused by default). funny

**Comment by josephmachado** [comment]
Yep. The DAG by default is paused (this is in airflow config). And no tasks will be run if the DAG is in paused state.
